PKG_NAME = fdk-aac
PKG_VERS = 0.1.4
PKG_EXT = tar.gz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://downloads.sourceforge.net/opencore-amr
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = 

HOMEPAGE = http://www.linuxfromscratch.org/blfs/view/svn/multimedia/fdk-aac.html
COMMENT  = AAC library, which is purported to be a high quality Advanced Audio Coding implementation.
LICENSE  = BSD

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk

